
enchantmentNames:
  "0": "Protection"
  "1": "Fire Protection"
  "2": "Feather Falling"
  "3": "Explosion Protection"
  "4": "Projectile Protection"
  "5": "Thorns"
  "6": "Water Breathing"
  "7": "Water Walker"
  "8": "Water Worker"
  "9": "Sharpness"
  "10": "Smite"
  "11": "Bane of Arthropods"
  "12": "Knockback"
  "13": "Fire Aspect"
  "14": "Looting"
  "15": "Efficiency"
  "16": "Silk Touch"
  "17": "Unbreaking"
  "18": "Fortune"
  "19": "Power"
  "20": "Punch"
  "21": "Flame"
  "22": "Infinity"
  "23": "Luck of the Sea"
  "24": "Lure"
  "25": "Frost Walker"
  "26": "Mending"
  "27": "Binding Curse"
  "28": "Vanishing Curse"
  "29": "Trident Impaling"
  "30": "Trident Riptide"
  "31": "Trident Loyalty"
  "32": "Trident Channeling"


